#!/bin/bash

# Somehow PS1 might be unbound
: "${PS1:=> }"

if [ ! -e "setup.py" ]; then
   echo "E: Intended to be ran within a folder having setup.py" >&2
   exit 1
fi

set -eu

deactivate 2>/dev/null || :

py=3; 
if [ -n "${DLDEV_ENVIRONMENT_VERSION:-}" ]; then
    d=venvs/${DLDEV_ENVIRONMENT_VERSION}
else
    d=venvs/dev$py;
fi

rm -rf "$d"; 
python$py -m virtualenv --python=python$py  --system-site-packages $d 
source "$d/bin/activate"
pip3 install -e .

echo "I: Run  source $d/bin/activate  to activate this virtualenv"
